---
# Default profile is dev
spring.profiles.active: dev

spring.data.mongodb.host: mongo

telegram:
  token: ${BOT_TOKEN}

ruz:
  base_url: 'https://ruz.hse.ru/api/'

youtube:
  key: ${YOUTUBE_KEY}

---
spring.profiles: dev

